// Copyright 2024 Edward Morgan
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


#ifndef UVMS_CONTROLLER__UVMS_CONTROLLER_HPP_
#define UVMS_CONTROLLER__UVMS_CONTROLLER_HPP_

#include <memory>
#include <string>
#include <vector>

#include "uvms_controller/uvms_base.hpp"
#include "uvms_controller/visibility_control.h"
// auto-generated by generate_parameter_library
#include "uvms_controller_parameters.hpp"

namespace uvms_controller
{

class UvmsController : public UvmsControllerBase
{
public:
  UVMS_CONTROLLER_PUBLIC
  UvmsController();

protected:
  void declare_parameters() override;
  controller_interface::CallbackReturn read_parameters() override;

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
};

}  // namespace uvms_controller

#endif  // UVMS_CONTROLLER__UVMS_CONTROLLER_HPP_
