// Copyright 2020 PAL Robotics S.L.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef UDWADIA_KALABA_CONTROLLER__UDWADIA_KALABA_CONTROLLER_HPP_
#define UDWADIA_KALABA_CONTROLLER__UDWADIA_KALABA_CONTROLLER_HPP_

#include <memory>
#include <string>
#include <vector>

#include "udwadia_kalaba_controller/udwadia_controllers_base.hpp"
#include "udwadia_kalaba_controller/visibility_control.h"
// auto-generated by generate_parameter_library
#include "udwadia_kalaba_controller_parameters.hpp"

namespace udwadia_kalaba_controller
{
/**
 * \brief Udwadia Kalaba controller for a set of joints and interfaces.
 *
 * This class forwards the reference signal down to the control to compute command torques for set of joints or interfaces.
 *
 * \param joints Names of the joints to control.
 * \param interface_name Name of the interface to command.
 *
 * Subscribes to:
 * - \b reference (std_msgs::msg::Float64MultiArray) : The reference to achieve.
 */
class ForwardCommandController : public ForwardControllersBase
{
public:
  UDWADIA_KALABA_CONTROLLER_PUBLIC
  ForwardCommandController();

protected:
  void declare_parameters() override;
  controller_interface::CallbackReturn read_parameters() override;

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
};

}  // namespace udwadia_kalaba_controller

#endif  // UDWADIA_KALABA_CONTROLLER__UDWADIA_KALABA_CONTROLLER_HPP_
