// Copyright (C) 2024 Edward Morgan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.


#ifndef UVMS_CONTROLLER__UVMS_CONTROLLER_HPP_
#define UVMS_CONTROLLER__UVMS_CONTROLLER_HPP_

#include <memory>
#include <string>
#include <vector>

#include "uvms_controller/uvms_base.hpp"
#include "uvms_controller/visibility_control.h"
// auto-generated by generate_parameter_library
#include "uvms_controller_parameters.hpp"

namespace uvms_controller
{

class UvmsController : public UvmsControllerBase
{
public:
  UVMS_CONTROLLER_PUBLIC
  UvmsController();

protected:
  void declare_parameters() override;
  controller_interface::CallbackReturn read_parameters() override;

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
};

}  // namespace uvms_controller

#endif  // UVMS_CONTROLLER__UVMS_CONTROLLER_HPP_
